### ISSUE TITLE
Random players icons do not show consistently in multiple locations

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#202]
Random players Icons do not show correctly in the following places:
- Rankings page
- Live game component
- Match history

![infi1](https://user-images.githubusercontent.com/40397054/96870965-8cb92e80-1469-11eb-9523-4451db0db9b6.PNG)

![infi2](https://user-images.githubusercontent.com/40397054/96870976-8f1b8880-1469-11eb-8a95-fd0acba97d43.PNG)

![infi3](https://user-images.githubusercontent.com/40397054/96870986-92167900-1469-11eb-9ebe-ff8670b07436.PNG)

**Comment by marco93f** [comment]
There's nothing wrong in showing the Reforged mud golem icon for live games and in match history, but that should not be the case for the rankings page. Just look at IFFI#1561, for instance: on his profile he has the Reforged sheep icon, but in the rankings page he still has the mud golem. You always want to show the profile icon.

**Comment by Cepheid-UK** [comment]
Sheep is the default icon if the player doesn't select any other, right? 

Should the mud-golem in the rankings/matches grid be switched to a sheep if the player hasn't selected an icon?

**Comment by Cepheid-UK** [comment]
Did a6ae5af fix this?
