### ISSUE TITLE
Show rankings by country

### ISSUE THREAD

**Issue by abeninski** [w3champions/website#208]
It would be awesome if we could see rankings by country.

Example UI:
1) User clicks on a flag in rankings page and is redirected to a new page.
2) New page has rankings grid sorted descending by Grand Master players on top and Bronze players on the bottom. If there are no Grand Master player then Master is first and so on.
3) Leagues are separated with league name and title.

**Grand Master**
1. Rank 1
2. Rank 2

**Master**
1. Rank 1
2. Rank 2
3. Rank 3

**Diamond 1**
1. Rank 1
2. Rank 2
3. Rank 3

**Diamond 2**
1. Rank 1
2. Rank 2
3. Rank 3

**Comment by JKoehler11** [comment]
Since we already have their country on the rankings page, I could see this as just a country filter.

I'll take a look into this quick to see how feasible this is.

**Comment by Cepheid-UK** [comment]
Refrogged actually do this for French players and their implementation is how Abe described it.

![refrogged](https://user-images.githubusercontent.com/40397054/99060090-6f264300-2597-11eb-9d2a-aecb485d0529.PNG)

**Comment by abeninski** [comment]
They do it using my tool 👍

**Comment by jj-apps** [comment]
Not sure if anyone is still working on this. But since it is widely requested I'm going to start working on it now.

**Comment by modmoto** [comment]
nice one =)

**Comment by jj-apps** [comment]
Something like this okay?
![image](https://user-images.githubusercontent.com/3699727/103959325-9ec37880-510c-11eb-88e0-be2ef9fc23f2.png)

**Comment by abeninski** [comment]
Just what I intended it should look. Great!
Are you separating by divisions?
