### ISSUE TITLE
End of season tournament profile badges

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#212]
It would be nice to reward end-of-season tournament participants with a badge on the profile similar to the season participation badge.

Design as well as implementation is needed.

![badges](https://user-images.githubusercontent.com/40397054/96875703-71512200-146f-11eb-85b4-eccc7f6fb7b5.PNG)

**Comment by jj-apps** [comment]
@Cepheid-UK Is there someone that could design the badge? Maybe something like the trophy icon in the menu? 
![image](https://user-images.githubusercontent.com/3699727/97529271-c6f46580-196c-11eb-9007-8608f47338b4.png)

**Comment by Cepheid-UK** [comment]
Talk to Riptide on discord, he designed our badges.

**Comment by jj-apps** [comment]
@Cepheid-UK 
![image](https://user-images.githubusercontent.com/3699727/98016146-dc2d2200-1dba-11eb-88df-d911c34a4a93.png)

Here is what Riptide came up with so far. 

He did ask if we wanted all participants to have a badge or just the top 3 (He made them Gold, Silver, and Bronze).

**Comment by Cepheid-UK** [comment]
These look pretty good, want to take a crack at implementing them?

In an ideal world, we'd tie these to the admin or tournaments page so that admins can assign these, but that might be a bit wider scope than this specific issue.

**Comment by jj-apps** [comment]
Yeah I'll give it a try.

He is going to create a 4th trophy for anyone that doesn't make the top 3, but was in the tourney.

**Comment by modmoto** [comment]
The absolute ideal world would be that we get them from the tournamnet winner dynamically. But that would also include linking the tournaments with the actual battletag. Right now it is only a string. But this would save us some time and would prevent errors/forgetting to assign these.

**Comment by Cepheid-UK** [comment]
made an issue #275 to cover this @modmoto it's a prerequisite for any further work on tournaments, and would help the admin page too. Nice suggestion.

**Comment by modmoto** [comment]
nice one

**Comment by jj-apps** [comment]
@Cepheid-UK @modmoto 

Updated images from Riptide:
![image](https://user-images.githubusercontent.com/3699727/98431546-89ca5a80-2073-11eb-9128-83af5586e60b.png)

There is a Gold, Silver, and Bronze trophy for 1st, 2nd, and 3rd place. All trophies have the season # on them.

He presented some choices for the rest of the tournament participants:
Option 1: Dark grey trophy
Option 2: Trophy colored based upon the "season color"

What is your preference on trophy colors for non-Top 3 participants? I think I like the dark grey trophy. I feel that having so many different colored trophies would be confusing.

Let me know. Thanks!

**Comment by Cepheid-UK** [comment]
I've learned to trust riptide's design sense, so go for it.

If you can get it implemented we can always tweak it.

**Comment by jj-apps** [comment]
@Cepheid-UK I just went to start this but I noticed that there are some existing tournament badge assets. Not sure who added them... but do we want crowns or trophies? The crowns don't have numbers so I'm not sure how you can tell which season they belong to. 

![image](https://user-images.githubusercontent.com/3699727/100142038-821afc00-2e50-11eb-921d-84bc2eb1f9f7.png)
![image](https://user-images.githubusercontent.com/3699727/100142140-a4147e80-2e50-11eb-9ac2-832e03b5281b.png)

**Comment by Cepheid-UK** [comment]
I think they were experimental and made when badges were first implemented but not used, Riptide should have the answer.

**Comment by zygissss** [comment]
done

**Comment by gustav87** [comment]
I'm not sure what was done in relation to this feature request, but we already have profile pictures awarded to players finishing first in the rankings for a season, and for the end of season tournament, there's a cash prize (depending on donations). Implementing this probably is not worth the time at the moment.
