### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#213]
We'd like to implement achievement functionality onto profiles, starting with some simple achievements such as win 25 games on a specific map or play AT with 5 different partners, that sort of thing.

The data on winrates and maps, and many other useful things is already available to the front end.

Design required: achievement icons, discuss with designers kenshin/riptide on discord.

**Comment by gDollaZ** [comment]
I started working on this.
I will talk to Kenshin/Riptide once I have something to show them.

**Comment by modmoto** [comment]
We should decide what kind of achievements we want to add. And dont forget, that we can use skins aswell, this might be cooler than profile pictures (maybe). But we should discuss it, because it might change the model.

**Comment by gDollaZ** [comment]
> We should decide what kind of achievements we want to add. And dont forget, that we can use skins aswell, this might be cooler than profile pictures (maybe). But we should discuss it, because it might change the model.

I took into account that we will want to add and/or modify existing achievements, so I was thinking of creating a way to edit something like a JSON file. We could keep the achievement definitions in there, and add or modify them as we see fit. The new code would use this file and compare the existing player data to see if any achievements have been reached using the rules in the JSON file.

**Comment by modmoto** [comment]
kk, seems like you got that =)
