### ISSUE TITLE
Improve Picked Hero Overview

### ISSUE THREAD

**Issue by phil-zxx** [w3champions/website#216]
I was wondering if it's worth updating the picked hero overview https://www.w3champions.com/OverallStatistics/heroes-winrates:
  1. Group by Race (HU, ORC, UD, NE & Tavern) and sort by picked hero count within each group. That way, it's a lot easier (and more intuitive) to find heroes in the graph. 
  2. Instead of showing a total count, show a percentage (normalised by race). That way, we can actually compare whether e.g. HU players choose AM more than NE players choose DH.

I've attached examples for 1on1 & FFA. Happy to help, if necessary.

![image](https://user-images.githubusercontent.com/32247590/96908988-47aaf180-1495-11eb-8482-77a224758390.png)

**Comment by abeninski** [comment]
Yeah good idea. Would be awesome if you can help with implementation.

**Comment by Cepheid-UK** [comment]
On the site we use ChartJS for all the graphs.

This PR should give some clues as to how it's implemented in ChartJS:

https://github.com/chartjs/Chart.js/pull/3563

**Comment by JKoehler11** [comment]
I will start working on this. I don't have permissions yet to assign this to myself.

**Comment by JKoehler11** [comment]
![image](https://user-images.githubusercontent.com/874269/97125134-e38c6580-1700-11eb-83ea-744e1f17075b.png)

Does this look close to what you expected? @phil-zxx

**Comment by modmoto** [comment]
Looks nice, how about one color per race? Makes the coloring more clear. For example between NE and UD, the colors are hard to distinguish. Like blue for HU, red orc, teal ne and purple ud. 
I assigned your name btw.

**Comment by phil-zxx** [comment]
I really like the look of it. Maybe also add some (white) space between each race; as in my original suggestion (since it helps visually to have each race in its own block).

**Comment by Cepheid-UK** [comment]
Looks really good!

**Comment by JKoehler11** [comment]
![image](https://user-images.githubusercontent.com/874269/97208063-b6839580-1788-11eb-89ff-eaff567915fc.png)

Yeah I agree it turned out well. I also changed the percent to be based on per race.

I think the only thing that would make it better is to add in filtering by season and so I'll add an issue for that.

**Comment by JKoehler11** [comment]
Without having the played race, the percentage will not be correct.

I think that the endpoint will need to be updated to return the played race as well.

The way it is now, when calculating by race, if they picked a tavern hero that will throw off the percentages. Also, this way one can filter by race as well.

I think it would also be helpful to filter by season.

**Comment by alocate** [comment]
there will always be an issue when a random player picks only tavern heroes. maybe filter out random players entirely? Should be less than 10% of games in solo.

**Comment by JKoehler11** [comment]
> there will always be an issue when a random player picks only tavern heroes. maybe filter out random players entirely? Should be less than 10% of games in solo.

Yeah I was thinking about how random and tavern heroes affected this.

My thought is that if we can get picked race and then actual race and group the data by that then we can add a drop-down to filter this in a meaningful way.

I think these dropdowns would need to be added to add more usefulness to the data:
- season
- race
 - for this I think it would contain this:
All
Human
Orc
NE
Undead
Random - Human
Random - Orc
Random - NE
Random - Undead

In the future it may be nice to have one for map as well.

**Comment by gustav87** [comment]
Completed.
