### ISSUE TITLE
Add ability to select a language

### ISSUE THREAD

**Issue by ghost** [w3champions/website#221]
Add translations for the website.
Add the ability for a user to select their language (auto select by browser's language selection).

https://kazupon.github.io/vue-i18n/

**Comment by Cepheid-UK** [comment]
We actually already include i18n in order to handle some other string conversions. Ty for the suggestion.

**Comment by modmoto** [comment]
we also have some strings translated allready. We had german at the start but did not go further  ;) But this would be nice indeed. Could also be a cool community effort to translate the texts. If a spanish user wants it spanish, he can just make a pr.

**Comment by JKoehler11** [comment]
I think for a non-developer creating a PR would be difficult. Probably not worth the effort to integrate with a translation website like CrowdIn.com either.

We could provide a spreadsheet with strings that need to be translated. Then a developer could update and create a PR per language.

We would need to create a fork that:
- Update all strings to be localized
- Add documentation on how to translate for non-developers
- Create a spreadsheet with strings to be translated

**Comment by modmoto** [comment]
jeah seems fine. And you are right, prs do not work well here xD

**Comment by zygissss** [comment]
done

**Comment by ryantzor** [comment]
Do you guys need help grooming these issues (this one looks closed? I'd love to start contributing and I figure a good place to start is looking at the issue tracker
![image](https://user-images.githubusercontent.com/2904417/187121273-9c4944fa-77e1-4150-b91b-871db4d7ca37.png)

**Comment by gustav87** [comment]
> Do you guys need help grooming these issues (this one looks closed, see img)? I'd love to start contributing and I figure a good place to start is looking at the issue tracker ![image](https://user-images.githubusercontent.com/2904417/187121273-9c4944fa-77e1-4150-b91b-871db4d7ca37.png)

Hey @ryantzor, sorry for the late reply. You are very welcome to contribute. Just contact me (Kovax) on our Discord. https://discord.gg/n2WZS6zx
