### ISSUE TITLE
Match history sorting

### ISSUE THREAD

**Issue by marco93f** [w3champions/website#230]
Not all games are sorted correctly. Check out for example games played on June 2 and May 14 during season 1. Also, match history from May 15 to 22 is missing

**Comment by modmoto** [comment]
In season 1 we had a lot of server issues that led to hacks to restore the data somehow. This is the reason the timeline is fucked sometimes. We want to close this as "not fixable" because we are missing the actual data?

**Comment by Cepheid-UK** [comment]
Not worth the fix in my opinion.
