### ISSUE TITLE
Clan creation

### ISSUE THREAD

**Issue by marco93f** [w3champions/website#234]
As of now 6 players are required to accept the invitation from a clan chieftain in order to create the clan and be members. Ideally you don't want to treat clans with less than 7 members as "real" clans, so their clan tags shouldn't be showed on the rankings, the list of signees shouldn't be publicly available in profile/clan and ultimately should get disbanded after a certain amount of time if they don't reach 7 members, so that it's possible for others to use the previously locked name/tag.

**Comment by zygissss** [comment]
done
