### ISSUE TITLE
Incorrect Stats by gamemode (2vs2)

### ISSUE THREAD

**Issue by marco93f** [w3champions/website#236]
Player profile > Stats by gamemode > 2vs2 AT
Currently the given values for MMR and RP respectively are taken by averaging across all teams regardless of how many games have been played with each team.

Example: Team A with 1000 MMR and 100 games, B with 2000 MMR and 50 games should be averaged into 1333 MMR (NOT 1500).

**Comment by Cepheid-UK** [comment]
Linked to #245

**Comment by zygissss** [comment]
done
