### ISSUE TITLE
Profile 2v2AT card shows different MMR/RP to the stats grid

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#245]
The 2v2 AT card on a players profile displays a different MMR & RP to the one in the player's stats grid.

![different](https://user-images.githubusercontent.com/40397054/97463299-83cbcf80-1937-11eb-829f-cccf8fe61fd1.PNG)

**Comment by jj-apps** [comment]
@Cepheid-UK It's because he has multiple teams of 2v2 AT.

Stats by game mode is combining them.

**Comment by Cepheid-UK** [comment]
Yeah, this is a combined issue with the stats service, we should really be more clear about why those two stats are different numbers.

**Comment by gustav87** [comment]
I've checked a few profiles and I don't see this issue. Reopen if it still exists and there's an example.
