### ISSUE TITLE
Match summary page could display information better

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#262]
The summary page for a match was designed for 1v1 and has not been redesigned much as 2v2/4v4/FFA were added, as a result it's quite difficult to parse the information on it.

e.g. 4v4 game:
![matchsummary](https://user-images.githubusercontent.com/40397054/97863988-cad30f80-1cff-11eb-91af-3a14d8601c36.PNG)

I think a redesign to make the information easier to read would be great. Perhaps a table format?

**Comment by thealexwilson** [comment]
I'm taking a look at this now

**Comment by Cepheid-UK** [comment]
#320 fixes
