### ISSUE TITLE
Chinese (or Infi's?) Flag does not show up in /matches

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#264]
![infi](https://user-images.githubusercontent.com/40397054/97885474-50b28300-1d1f-11eb-9953-1f9ae9cc332d.PNG)

Unsure if this is specific to user, or all chinese flags.

**Comment by Cepheid-UK** [comment]
![Screenshot_20210110-181952_Chrome](https://user-images.githubusercontent.com/40397054/104131773-8a7fb580-5370-11eb-9895-584467e48a39.jpg)

Witnessed this bug in the wild again. Seems to affect Chinese players only.

**Comment by aaronjewell** [comment]
This is likely caused by a failure to obtain location information. This can be confirmed if a player with a known issue can report back the results of visiting https://www.cloudflare.com/cdn-cgi/trace

**Comment by aaronjewell** [comment]
I wonder if we just assign CN as a default?

**Comment by abeninski** [comment]
We should use what we have previously in the db if current match contains no country.

**Comment by aaronjewell** [comment]
👍  Digging through when to resolve that, and what a complete fall-through would look like if no matches contain country.

**Comment by abeninski** [comment]
No need to go through matches. It is saved in personal settings

**Comment by zygissss** [comment]
done
