### ISSUE TITLE
Admin page is buggy

### ISSUE THREAD

**Issue by alocate** [w3champions/website#268]
Known issues:
-delete a ban entirely (remove entry) does not work, it never gets saved
-sometimes, when one tries to update a ban, it gives minus 1 day randomly when it saves
-when adding multiple entries, it gets very buggy, data can be lost/isn't saved between individual bans are added

**Comment by alocate** [comment]
This is linked to issue #223 - but as a first step, getting rid of those bugs would already go a long way towards the usability of this page.

**Comment by modmoto** [comment]
I am doing some rework here and want to add some more fun stuff.

What else do you have in mind? @floss2xdaily

**Comment by Miyagi1337** [comment]
Sorry I missed this discussion, I'm new to GitHub :D

**Admin page**
- Fix deleting/editing entries not saving correctly. Additionally deleting entry sometimes does not lift W3C Lounge chat ban and only unbans from playing.
- Show timer for server update/sync/refresh/ticks. It would be great to see exact timestamp of when ban and unban occurs.
- Reveal account lookup functionality on admin page. This requires @abeninski permission.

**W3C Lounge and menu**
- Show ban message when banned: I don't even know what it looks like when someone is banned. Some users report that they just see a blank menu and start to troubleshoot for other errors, then come very confused to Discord to figure out why. The ban message could be localized with multi-language message: _"You are banned. Go to Discord and message Miyagi or Floss2xdaily to figure out why or appeal"_
- Moderator ability to time out single messages in W3C Lounge: _"Message deleted by moderator."_
- Hide moderator BattleTag on right click in W3C Lounge. I would like to be anonymous
- Fix my alias as "Miyagi" no longer working in W3C Lounge. It displays my BattleTag again like before abeninski added it.
- User ability to right-click and mute/squelch in W3C Lounge or use chat command !mute/squelch/ignore PLAYER. Currently the only option to avoid reading messages from a player in W3C Lounge is to close the chat completely.

**Ingame**
- Global chat mute
- Simple english rules in 2v2 and 4v4 loadscreen: _"No TK, No leaving, No AFK, Teamwork, Play to win"_ or similar. Some players, especially non-english speakers, are surprised and confused that there is moderation

**Fun stuff**
- Additional chat commands: !stats PLAYER, !who PLAYER, !time
- Seperate 25 W3C Friends list with chat commands: !f/friend add PLAYER, !f/friends remove PLAYER, !f l/list, !ignore PLAYER, !unignore PLAYER, !o igw
- Liquipedia player data import for chat commands: !who Moon - Return: Jang "Moon" Jae Ho (born December 14, 1986) is a professional Korean Night Elf player.
- HTML support for chat like before new UI. I loved to be able to use simple HTML functionality like <img src /> and <marquee />

**Comment by Miyagi1337** [comment]
> I am doing some rework here and want to add some more fun stuff.
> 
> What else do you have in mind? @floss2xdaily Wanted to make the feature to delete a chat message. Is there anything else you guys would benefit from?
> 
> I was thinking color coding the list, for chat and total bans. And then greying out bans that have run out. Also order by creation date or end date per default?

Color coding is a great idea to distinguish between active and expired bans at a glance.

I think it should be ordered by end date. Latest entry to end in top.

**Comment by modmoto** [comment]
How about order by creation date and then you can sort by ban date later? I guess the question "why was i banned" comes quite often and then you have the recents bans right there? If you have just created a long ban, it would never show up for example (only whn scrolling).

**Comment by Miyagi1337** [comment]
That sounds good too. Honestly it is not that important because I just look up the name or BattleTag with Ctrl + F

Ok sounds great about site improvements! I haven't noticed any problems yet.

It's no rush with chat ban. Behavior is better and I rarely use it. Ideally it would be great to be able to ban from W3C Lounge within the UI by right-click or chat command in addition to single comment timeouts.

I will make sure to watch this repo so I see your replies faster :)

**Comment by Miyagi1337** [comment]
![bannotworking](https://user-images.githubusercontent.com/74210207/101228650-e6ce2600-369c-11eb-8f7e-dfa5504a11dc.png)

User not affected by active ban

**Comment by modmoto** [comment]
The chat ban is broken right now, unfortunatelly. This should be fixed in the next days.

**Comment by Miyagi1337** [comment]
> The chat ban is broken right now, unfortunatelly. This should be fixed in the next days.

Floss and I will stop using chatbans until it's fixed

Another issue is that some users seem to be unaffected by regular bans, not chat bans. Here are 3 examples of accounts that have played games during active ban:
MrGannicus#21109
OT100U#2291
POKINHO#21216

> You can also subscribe to this issue on the right sight, so you get mails, if something happens here.

Yes I get a notification when you reply now :)

**Comment by abeninski** [comment]
We should redesign admin page to have menu like this
https://www.theknowledgeguru.com/dev/wp-content/uploads/2017/12/Player-mgmt-1.png
and inside every menu page we can put tabs

**Comment by Cepheid-UK** [comment]
Admin page has been changed so much that these discussions are no longer relevant, we can make new issues for specific admin page issues.
