### ISSUE TITLE
Issues concerning maps

### ISSUE THREAD

**Issue by marco93f** [w3champions/website#271]
- Sometimes there are two entries for Last Refuge in /player/?/statistics (e.g., "Last Refuge" and "mapNames.lastrefuge.anon" - see [here](https://www.w3champions.com/player/Toxi%2321818/statistics));
- There are two occurrences for Autumn Leaves in the "Select Map" dropdown menu, in [/OverallStatistics/winrates-per-race-and-map](https://www.w3champions.com/OverallStatistics/winrates-per-race-and-map);
- Golems in the Mist is missing the LV suffix. A potential fix should affect the /Matches, /player/?/matches and /OverallStatistics pages.

**Comment by aaronjewell** [comment]
Looking to solve this issue for #309  and then implement across /Matches, /player/?/matches and /OverallStatistics in subsequent PR's.

For duplicate translations of the map labels (Autumn Leaves), perhaps add a suffix to the translation, possibly surrounded by parentheses. i.e. `Autumn Leaves (201016)`. I don't love this solution, and am open to alternative ideas on how players would know and identify the difference between the versions. Merging the maps for display purposes seems like a tricky endeavor.

For lastrefuge.anon, the dot interferes with the translation to its label, the least repetitive option is to change the object delimiter from `.` to something such as `#` so we could say `mapNames#lastrefuge.anon` to get the label correctly. I don't know the dataset well enough to know if it is future-proof enough to use `#` but unless we translate something like battleTags, it seems safe. This would require changing all the translation calls using the `.` object delimiter, but would be fine afterwards. If we don't change the delimiter, we'd have to transform the map key before each translation, which feels sub-optimal to me and easily missed.

Golems in the Mist looks alright from my perspective, there are two translation keys:
>     golemsinthemist: "Golems in the Mist",
>     _goleminthemist_lv_anon: "Golems in the Mist LV",

**Comment by aaronjewell** [comment]
The lastRefuge.anon defect and Golems in the Mist LV issues were fixed, I believe in response to #235. Handling duplicate names is still an issue for Autumn Leaves.

**Comment by Cepheid-UK** [comment]
This requires a DB merge to fix duplicate AL names I think, we'll just have to accept it until someone with DB skills takes interest :D
