### ISSUE TITLE
Link the tournament grid and admin pages with database-stored Battlenet tags

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#275]
Every player we will ever want to record on the tournments page will have a Battle.net tag associated with them on the W3Champions system, we should link these together.

Not only will this make the tournaments page easier to use, but is one of the requirements for automated tournaments.

the exact implementation to be discussed via discord.

**Comment by modmoto** [comment]
I assigned myself but I am not working on this right now. Wanted to keep this in my history because this seems like a feature I would like to do =) If anyone goes first, no hard feelings, though.

**Comment by zygissss** [comment]
done
