### ISSUE TITLE
Add option to sort ongoing games and finished games by avg MMR and filter by map

### ISSUE THREAD

**Issue by HelpstoneX** [w3champions/website#277]
- makes it easier to spot high level games (to check livestreams or watch vods afterwards)
- can be used to find matches on a specific map to see how it gets played and which players don't have it vetoed (especially useful for mapmakers of the new maps)
- also very useful to check how well the matchmaking works on higher/ lower levels

**Comment by jensk1** [comment]
Currently the api is only able to load the matches descending by ID of the match. 
If this feature is needed and approved I can extend the Statistics service, so it will be able to also return the matches sorted by map/mmr maybe duration.

**Comment by modmoto** [comment]
jeah why not. Extending the search in the statistic service should be really straight forward. Maybe mmr is a little difficult, but mapname is easy.

**Comment by jensk1** [comment]
You are right, map is pretty easy. MMR is kinda hard. Because MMR is structured in the Players and not directly in the Matchup Object. I thought best way is to query by Old MMR of all players participating in a match and average it. But this is not queriable by the Mongo DB driver. So maybe one possibility is to add the average MMR of a Game directly to the matchup in the DB, so it is queriable?

**Comment by alocate** [comment]
another issue is that MMR is affected by resets - for another purpose (to computed expected winrates), we are thinking of adding a shadow MMR calculation which is not affected by resets (which would not be used anywhere else). this looks like we could kill two birds with one stone too, as we could also create an "average shadow MMR" for each match as the migration is done?

**Comment by alocate** [comment]
if you want a more simple solution though, I think ordering games by MMR of the first player could work?

**Comment by jensk1** [comment]
I will try it by ordering it by MMR of the first player, think this can be especially for 2v2 and 4v4 not the optimal ordering.
Does the MMR reset also affect the OldMMR attribute of Players in the matchup Collection? Think this is a snapshot of the Matchmaking. But still shadow MMR would be the better solution

**Comment by Cepheid-UK** [comment]
Perhaps ordering by MMR is a job for the new python app?

**Comment by modmoto** [comment]
we should let this in the stats service, as the mmr service should be used for business logic. I would not call two backends from the frontend just to do some sorting. I think it would be fine to call it asynchronously in the handlers, maybe, but not more than that. Just to keep the dependencies a little lower.

**Comment by gustav87** [comment]
@Cepheid-UK Is this considered done you think?
