### ISSUE TITLE
Last 10 games performance should be hidden from AT tab for past seasons

### ISSUE THREAD

**Issue by marco93f** [w3champions/website#282]
While browsing /player/? and /player/?/at-teams for the current season, last 10 games performances are hidden from all the arranged team tabs. When you switch to a prior season, though, they do show up. They should be hidden because you get the same string no matter who you played with.

**Comment by SergeyKhval** [comment]
Fixed in #285

**Comment by marco93f** [comment]
@SergeyKhval Good job! By the way, sorry for missing it earlier, but apparently the same happens in /player/?/clan: it should be hidden there too.

**Comment by SergeyKhval** [comment]
fixed it for clan pages

**Comment by Cepheid-UK** [comment]
Can this be closed now @marco93f?

**Comment by zygissss** [comment]
done
