### ISSUE TITLE
Impossible to search for 2vs2 AT games in match history

### ISSUE THREAD

**Issue by marco93f** [w3champions/website#283]
Since the AT/RT merge (somewhen during season 3) all 2vs2 games are labelled as "2vs2", making no longer any distinction between AT and RT. Normally, as it used to be, "2vs2" should return RT games and "2vs2 AT" AT games.

**Comment by gustav87** [comment]
"Fixed" by removing the AT selection from the dropdown. https://github.com/w3champions/website/pull/839
