### ISSUE TITLE
Can't invite former members to clans

### ISSUE THREAD

**Issue by marco93f** [w3champions/website#284]
If a player joined your clan but later left it for whatever reason, the clan chieftain can't invite him back ("can't invite player twice").

**Comment by modmoto** [comment]
Do you have an example? I can not reproduce this and there are also two scenarios where this is working.

**Comment by wkozuch** [comment]
This is potentially the same issue as listed in website-backend  [#154 Clans: Player who founded a clan leaves, then can't rejoin](https://github.com/w3champions/website-backend/issues/158)

**Comment by gustav87** [comment]
Fixed in website-backend.
