### ISSUE TITLE
Top live 1v1 matches Player names not readable when NE/UD theme is selected

### ISSUE THREAD

**Issue by weidenbach** [w3champions/website#314]
Top live 1v1 matches Player names not readable when NE/UD theme is selected
![unknown](https://user-images.githubusercontent.com/73471359/102723117-40be2500-4306-11eb-82b4-97806b86ebfc.png)

**Comment by aaronjewell** [comment]
Resolved by https://github.com/w3champions/w3champions-ui/commit/43062cf5d8061c64eefdab5000f33da30cca5e19

**Comment by cmavelis** [comment]
![image](https://user-images.githubusercontent.com/16199008/105891961-35ce7280-5fdf-11eb-9561-0aeacaf37e1d.png)
looks fine now

**Comment by modmoto** [comment]
true, will close
