### ISSUE TITLE
Random race is not correctly parsed in /Tournaments when editing matches

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#331]
![randomincorrect](https://user-images.githubusercontent.com/40397054/104166236-62389b00-53f2-11eb-903c-0251d3dc9236.PNG)

**Comment by Cepheid-UK** [comment]
Fixing this will require admin access, so you'll need to run the authentication service locally.

**Comment by cmavelis** [comment]
so this a data bug, not a display bug?

**Comment by modmoto** [comment]
no, you just have to make the ui think you are admin to see this view. There is an explanation in the readme of the website or website backend.

**Comment by cmavelis** [comment]
I mean the issue of it saying `races.undefined` -- shouldn't the data be `races.random`?

**Comment by modmoto** [comment]
should be yes, but I guess the enum does not get parsed correctly? But jeah, just a guess

**Comment by zygissss** [comment]
done
