### ISSUE TITLE
FAQ page blank

### ISSUE THREAD

**Issue by aaronjewell** [w3champions/website#344]
Accessing the FAQ displays the title and an empty panel.
[https://www.w3champions.com/Faq](https://www.w3champions.com/Faq)

Referencing a non-existant repository for the JSON data to fill in the questions.
```https://raw.githubusercontent.com/modmoto/w3champions-news/master/prod/faqs.json```

There is a valid copy at
[https://raw.githubusercontent.com/Miyagi1337/w3champions-news/master/prod/faqs.json](https://raw.githubusercontent.com/Miyagi1337/w3champions-news/master/prod/faqs.json)

**Comment by modmoto** [comment]
Oh wow, thanks for that, I thought i wiped it :D
