### ISSUE TITLE
Match History display bug - previously viewed person

### ISSUE THREAD

**Issue by cmavelis** [w3champions/website#350]
![image](https://user-images.githubusercontent.com/16199008/105938269-41dd2300-6025-11eb-9456-15dafb0a6f15.png)
After viewing WeaponX's match history, then going back to mine via clicking "Profile" in the upper right, then "Match History" it showed like this

**Comment by cmavelis** [comment]
actual history: 
![image](https://user-images.githubusercontent.com/16199008/105938681-bb751100-6025-11eb-9e90-66daa1a86cda.png)

**Comment by cmavelis** [comment]
WeaponX's history: 
![image](https://user-images.githubusercontent.com/16199008/105938928-31797800-6026-11eb-8ac0-1c4852de8f77.png)

**Comment by Right5** [comment]
Should be fixed
