### ISSUE TITLE
Can't see some matches details still

### ISSUE THREAD

**Issue by Qeenon** [w3champions/website#354]
https://www.w3champions.com/match/601586d47e9f54f8aa0be2fc - because of name spoofing 
(suggestion solution - show player names as is on score screen for this case, avoid undefined error)

https://www.w3champions.com/match/6015cfb77e9f54f8aa1f6d47 - no idea why

@jj-apps 

related https://github.com/w3champions/website/pull/328

**Comment by joleb** [comment]
**As a workaround** I'd suggest we should implement a default error handler if something like this happens.
like: "uh this didn't work as expected, we are working on that." - everything is better than a blank page :D

**Comment by Qeenon** [comment]
at least that but I'd prefer if website will display match details still

**Comment by modmoto** [comment]
Yes definitely,should not be all to hard aswell, the error occurs because of a [0] on the wrong location.

**Comment by joleb** [comment]
i will take a look at this :)

**Comment by joleb** [comment]
if no one is willing to check my pr, i'll close it soon, just fyi. merging the current master branch is kinda waste for me, if its not used anyways.

**Comment by modmoto** [comment]
you mean https://github.com/w3champions/website/pull/363?

**Comment by Cepheid-UK** [comment]
> if no one is willing to check my pr, i'll close it soon, just fyi. merging the current master branch is kinda waste for me, if its not used anyways.

Hey sorry man, we just have a lot to juggle. Ty for the PR.
