### ISSUE TITLE
Match Info Not Displaying

### ISSUE THREAD

**Issue by gDollaZ** [w3champions/website#366]
Example link leaves blank info section:
https://www.w3champions.com/match/6034205f7e9f54f8aae257b3

$ curl -X GET https://website-backend.w3champions.com/api/matches/6034205f7e9f54f8aae257b3

Seems to return the expected values....

Console error:

TypeError: e.scoresOfWinners[n] is undefined
    po https://w3champions.wc3.tools/prod/site/js/app.c5030843.js:1
    He https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    po https://w3champions.wc3.tools/prod/site/js/app.c5030843.js:1
    _render https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    r https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    get https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    run https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    Zn https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    pe https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    ce https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
chunk-vendors.5b35b4a3.js:63:12041
    ie https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    re https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    ee https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    _render https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    r https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    get https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    run https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    Zn https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    pe https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63
    ce https://w3champions.wc3.tools/prod/site/js/chunk-vendors.5b35b4a3.js:63

**Comment by joleb** [comment]
should be related to #354

**Comment by Cepheid-UK** [comment]
@joleb is this issue resolved going forward?

**Comment by joleb** [comment]
@Cepheid-UK  should be resolved, i added fallback values in case the api returns undefined.

**Comment by Cepheid-UK** [comment]
#354 is resolved but still some issues, @joleb offered this commit which fixed some issues but not others cb4783aeb81720e9435dda81b569732d262f4e60

**Comment by Cepheid-UK** [comment]
I recall this being fixed now @joleb? you can do the honours of closing this if so.
