### ISSUE TITLE
Footmen Frenzy Issue Collation

### ISSUE THREAD

**Issue by gDollaZ** [w3champions/website#379]
- FOOTMEN FRENZY matches: translation for map missing for maps column? mapNames.tmenFrenzyv5.8.0W3C

**Comment by Cepheid-UK** [comment]
Stats are not working correctly (we need to also multiply these numbers by 6)
![Screenshot_20210418-181839_Chrome](https://user-images.githubusercontent.com/40397054/115154499-0de92b00-a073-11eb-8ebd-f77259886874.jpg)

**Comment by Cepheid-UK** [comment]
Need a new match component for ongoing and completed matches:

![ffcomponent](https://user-images.githubusercontent.com/40397054/115229231-aed6f500-a10a-11eb-8798-76046575acf5.PNG)

Note this component is also used on the match history page on player profiles.

**Comment by Cepheid-UK** [comment]
Map selection for Footmen Frenzy is redundant.

![overallmaps](https://user-images.githubusercontent.com/40397054/115229336-d463fe80-a10a-11eb-922f-50ed317a8aca.PNG)

**Comment by Cepheid-UK** [comment]
Mapnames for the current crop of custom games are fixed.

**Comment by Cepheid-UK** [comment]
some of these issues are fixed, but we'll be closing the FF ladder soon, so they will not be relevant.
