### ISSUE TITLE
Minor - widen box for MMR selector

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#394]
Doesn't quite fit with some of the translated strings:

![selector2](https://user-images.githubusercontent.com/40397054/120799299-75314080-c536-11eb-8333-b165234be00b.png)

**Comment by kontrarian** [comment]
@Cepheid-UK I'll pick this one up. It looks like a breakpoint issue from a quick inspection.

**Comment by kontrarian** [comment]
It's avatarX on discord btw

**Comment by Cepheid-UK** [comment]
Thanks, and welcome!

**Comment by kontrarian** [comment]
I've created a PR #403 for this with some discussion

**Comment by Cepheid-UK** [comment]
closed by #403
