### ISSUE TITLE
"Europe" region selector is unecessary

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#402]
Since we removed the regions, we no longer need to have "Europe" as a selector on the website. (Picture shows on the /Rankings view but it appears in a few other locations too, profile, stats iirc)

I believe the database still keeps data compatible with this region info, so for now we should probably just make the UI change to just remove this selector for now.

From memory, Vuex stores what region you're in, but we can just default everyone to "Europe" (and tbh, maybe we should just rename it to "Worldwide" or something on the enum.

![europeselector](https://user-images.githubusercontent.com/40397054/126967184-1bfe5ef5-cf58-43ec-8d2e-50176c8294e9.PNG)

**Comment by kontrarian** [comment]
Looks like the regions were merged in season 6. What if we just hide the region selector for season > 5, that way players can still see rankings old seasons?

**Comment by Cepheid-UK** [comment]
> Looks like the regions were merged in season 6. What if we just hide the region selector for season > 5, that way players can still see rankings old seasons?

This is a good solution 👍

**Comment by Cepheid-UK** [comment]
closed with #431 ty @Raswanson01
