### ISSUE TITLE
Dark logo on dark theme if no race theme is selected

### ISSUE THREAD

**Issue by kontrarian** [w3champions/website#405]
If you visit w3champions for the first time and have no race theme set in your local storage the default theme is undead but the w3champions default logo is black which looks odd.

We should either use a default light theme or alternatively use a light logo by default

<img width="1425" alt="Screenshot 2021-07-26 at 14 33 44" src="https://user-images.githubusercontent.com/7984606/126997871-b6d5662e-9f9c-428f-b1b0-d06350a8b985.png">

**Comment by Cepheid-UK** [comment]
![lightlogo](https://user-images.githubusercontent.com/40397054/127161385-c63b129d-a91c-4866-8f50-755e5c35925e.PNG)

There is a dark mode logo, I've definitely seen this issue before but never properly looked into what was causing it.

**Comment by kontrarian** [comment]
Yeah, I can replicate it by removing the `theme` key from local storage and refreshing.

I'll pick this up, I suspect it's an easy fix
