### ISSUE TITLE
Winrates tab doesn't fetch data on load

### ISSUE THREAD

**Issue by kontrarian** [w3champions/website#406]
If we go to statistics on the navigation bar and then select the Winrates tab, no data is loaded.

If we then go to the MMR tab and then back to the Winrates tab the data is available. I suspect the MMR tab does a fetch for the data but not the Winrates tab.

<img width="1425" alt="Screenshot 2021-07-26 at 14 37 36" src="https://user-images.githubusercontent.com/7984606/126998562-39c2bde6-1c2a-452a-be73-97180af1f6b6.png">

**Comment by Cepheid-UK** [comment]
I believe this is a bug with vue router. I think we had a similar tab bug on profiles iirc.

**Comment by kontrarian** [comment]
I'll dig into this one since it gives me a chance to get familiar with more vue stuff.

Do you know if that old profile bug still exists (or who I can check with about it)? I've poked around but didn't see anything that stood out.

If it's still there it might be worth solves both issues at the same time since it's probably related

**Comment by Cepheid-UK** [comment]
I'm afraid it's very abosolute back of the memory stuff.

I can't really recall, but it would probably take some digging into how v-tabs interacts with the router to figure out, as I think sometimes it's not re-requesting data when it should be.

**Comment by kontrarian** [comment]
All good, we can deal with it if and when it comes up. I'll see what I can do about this issue so long
