### ISSUE TITLE
Navbar breakpoints need to be adjusted

### ISSUE THREAD

**Issue by iamyemeth** [w3champions/website#407]
The navbar currently has 3 major breakpoints.

1. Show everything in the navbar
<img width="1208" alt="Screenshot 2021-07-26 at 14 42 50" src="https://user-images.githubusercontent.com/7984606/126999431-939c7c7a-9d4c-4f0e-87d9-be43c42b2c19.png">

2. Show everything but the w3champions logo
<img width="876" alt="Screenshot 2021-07-26 at 14 42 35" src="https://user-images.githubusercontent.com/7984606/126999460-f0bfd656-7bd1-4617-9e9b-05fb8cd3a521.png">

3. Show only the icon links and no logo
<img width="553" alt="Screenshot 2021-07-26 at 14 42 09" src="https://user-images.githubusercontent.com/7984606/126999481-2d286153-6984-4754-905e-575a88002984.png">

The actual breakpoints for these 3 views need to be adjust so there is no cropping of links or navbar scrolling as below. The core idea is that we need to remove the w3champions logo as soon as there is not enough space for all the links and then drop the text links as soon as there is not enough space.

**Comment by Cepheid-UK** [comment]
I'd definitely like to see this cleaner. If anyone has any better ways to breakpoint the navbar I'd welcome it, it takes up a lot of horizontal space.
