### ISSUE TITLE
Creating a new ban in the admin panel over-writes previous bans for same bnet ID.

### ISSUE THREAD

**Issue by ShearW3** [w3champions/website#433]
I noticed one of the players I previously banned from a certain game-mode was overwritten by a new ban from a different admin. The new ban was for a different game mode with a punishment that expired sooner. This essentially caused the player to be unbanned immediately from the game-mode in which I banned them from. 

Its also entirely possible I may have overwritten other admin's bans and since this incident, I am now using ctrl+f and searching for the username before banning any players, I don't mind and this is easy to do but I think not everyone is currently aware this is possible and it happens on accident. I certainly didn't know until I chanced upon it.

Suggestion; When creating a new ban, after filling in the bnet ID field perform a check and notify the admin if player is currently serving another ban so that it doesn't accidentally become overwritten.

**Comment by alocate** [comment]
I agree, this is worth improving. ban should be about each single ban (multiple entries per user) if possible. there's another bug that has existed forever, when you open an ongoing ban and save it again, the date does back one day.

**Comment by Cepheid-UK** [comment]
There is a task to rework the ban list, so we are searching individual players, and we can handle much easier with that workflow. If anyone would like to assist, I'm currently writing tests for the backend right now.

**Comment by gustav87** [comment]
There's battletag autocomplete and ban search now. Overwriting a ban is still possible, but solving that seems a bit difficult to integrate with smurf checking. Closing as completed!
