### ISSUE TITLE
Missing translation for menu "Account"

### ISSUE THREAD

**Issue by amacado** [w3champions/website#438]
String translations for `View Profile` and `Logout` are missing:

![image](https://user-images.githubusercontent.com/8781699/140669145-139cf666-0176-45f4-b216-867e3846df92.png)

https://github.com/w3champions/website/blob/2f9ccc353a2d97aeb77b0d8db7f17ae9221bd81f/src/App.vue#L62-L67

**Comment by godrien** [comment]
PR to fix this issue:

https://github.com/w3champions/website/pull/483

**Comment by zygissss** [comment]
done
