### ISSUE TITLE
Strange behaviour on statistics page: dropdown "games per day"

### ISSUE THREAD

**Issue by amacado** [w3champions/website#441]
On the statistics page: When any value in the dropdown "games per day" is selected, the chart will disappear.

![image](https://user-images.githubusercontent.com/8781699/143321727-97fbd6ca-3f66-4bd6-b818-d3f62d59eb73.png)
![image](https://user-images.githubusercontent.com/8781699/143321764-e47a9f63-33fe-4143-93d7-2dfb24656750.png)

This behaviour is based on this script:
https://github.com/w3champions/website/blob/97c19c448c66bdeb078091992e3c2564a802fd9b/src/components/overal-statistics/tabs/PlayerActivityTab.vue#L37

I have no idea why this was introduced, maybe someone has an idea?

**Comment by Cepheid-UK** [comment]
I might have introduced a bug with this commit: 7d64aaf 

I was refactoring the game mode selector to use translation strings.

An outstanding task would be to abstract the `gamemode-selector` functionality into a universal component and apply that across the site, it would make inconsistent things like this less of an issue.

If anyone reading this wants to take it up, check out the commit above, ask me on disc or @ me here.

**Comment by kangaro0** [comment]
If it is okay, i will pick this one up. Generally new to vue.js and want to get to know the api. If someone else comes up with a solution faster or is already working on this, just let me know. 

Regards,
kangaro0

**Comment by abeninski** [comment]
I think it's already fixed

**Comment by zygissss** [comment]
done
