### ISSUE TITLE
fix overlapping players in teams in rankings page

### ISSUE THREAD

**Issue by abeninski** [w3champions/website#444]
![image](https://user-images.githubusercontent.com/884808/147651628-8363725a-4773-4b3e-8ff7-5c18b41517f7.png)

**Comment by Cepheid-UK** [comment]
Should just be some styling in or around this component:

https://github.com/w3champions/website/blob/master/src/components/matches/PlayerMatchInfo.vue

**Comment by Cepheid-UK** [comment]
For some additional info, we also use this npm lib:

https://www.npmjs.com/package/vue-country-flag

In the past when I've tried to do an `npm update`, this has a breaking css update, so if you could update that package and resolve that at the same time, that would be great.

**Comment by Cepheid-UK** [comment]
resolved by #445
