### ISSUE TITLE
When one player from a team is streaming, it shows them all as streaming

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#451]
![image](https://user-images.githubusercontent.com/40397054/147982293-e223eb76-5ed8-4321-ad09-4261520023ae.png)

When a player is streaming their game, their teammates show as having active twitch streams, directing to twitch.tv/null.

**Comment by godrien** [comment]
@Cepheid-UK twitch icons are not showing on prod version. https://github.com/w3champions/website/issues/451 also fixes it

**Comment by Cepheid-UK** [comment]
#479 fixes.
