### ISSUE TITLE
"Game modes" column on the "Banned Players" Table show the ENum value instead of the name of the game mode

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#492]
When you ban a player the grid shows the game mode they are banned from with the ENum value like this:
![image](https://user-images.githubusercontent.com/40397054/164022601-2ffb7a98-a606-40c9-91bb-48ffc61454e2.png)

When editing or creating a new ban, the text correctly shows in the GameMode section of the dialog:
![image](https://user-images.githubusercontent.com/40397054/164022774-bc541448-8a19-4ae6-91d6-d65c4de75040.png)

Would be nice if the main table could show this text value.

Component file: https://github.com/w3champions/website/blob/master/src/components/admin/AdminBannedPlayers.vue

To test this fix you'll probably need to follow the instructions in the README to set yourself as an admin, and set the relevant functions to return some dummy data inside the component for testing.

I can send some dummy ban JSON data for you to work with if you need.

**Comment by carbohydrate** [comment]
Took a look at this one.  Think I got it working, but did not want to actually test creating a new ban and pushing it to the api (not even sure I could as I'm not an admin).  Commented out the function that does that and logged it and it seams to be working as expected.  Fixed banEndDate width as well.

Made the assumption that if gameModes is null or an empty array it means banned from all modes.

<img width="385" alt="banGameModes" src="https://user-images.githubusercontent.com/1137823/169724113-f84f78d9-4634-42c9-8692-932cd2280c1b.png">
