### ISSUE TITLE
Better profile search function

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#493]
To find a player you must go to the ranking page and search their battletag, then click the battletag, this scrolls the user to the location they are in the rankings, then they can click that players profile.

This is not good UX.

I'd like it if we could have a better player search function on the nav bar along the top:
![image](https://user-images.githubusercontent.com/40397054/164024385-6b53afaa-c881-44c0-8986-06268ca6c96c.png)

I picture this as a magnifying glass icon that drops down a search bar, the user can type with autocomplete, and the autocomplete dropdown will show a few details about each result:

- shows their profile picture
- shows their bnet tag
- the last 3 season badges on their profile? (as a quick indicator of their season activity)
- maybe a little icon showing what leagues they are in like a mini-ified version of the badges on profiles?

Clicking their card will take you directly to that players profile.

please enjoy this fantastic mockup of what I am thinking:

![image](https://user-images.githubusercontent.com/40397054/164029139-01277715-d81a-4cc0-9f2f-4d361de4ba1c.png)

This will require some backend work in website-backend, you can see how some search functions are done here:
https://github.com/w3champions/website-backend/blob/d38808fbafd2454394fa1ae6c96ae2d4bc6aafe5/W3ChampionsStatisticService/Ladder/RankRepository.cs#L43

We've implemented a few different searches in backend, so just ask for any guidance if the code doesn't speak to you.

**Comment by gustav87** [comment]
Closing this as it has been completed.
