### ISSUE TITLE
Missing instructions for setting up FLO at /getting-started manuals

### ISSUE THREAD

**Issue by nx518** [w3champions/website#500]
I followed the "MANUAL WINDOWS" at https://w3champions.com/getting-started/ precisely and now I'm able to connect to w3champions.

However when clicking on "FIND MATCH" I get "W3C FLO (HOSTBOTS) IS NOT CONNECTED." with "YOU HAVE CHOSEN TO PLAY ON FLO SERVER ONLY BUT YOU ARE NOT CURRENTLY CONNECTED TO FLO. START/RESTART W3C LAUNCHER TO CONNECT."

Please extend the manuals with a step how to setup flo manually without using the application.

**Comment by gustav87** [comment]
For most players, there should be no further instructions to play on w3c. Some people receiving a "not connected to flo" is a known issue, but can probably rarely be solved by the user, or it's a matter of disabling antivirus, vpn, etc, and is too complicated and case-per-case specific to be included in a manual. If a new user is having problems, the best course of action is to contact us on Discord. That could be included in the getting-started.
