### ISSUE TITLE
Use `pinia` to replace `vuex`

### ISSUE THREAD

**Issue by Rotzbua** [w3champions/website#609]
Vue2 is EOL by the end of the year. Migration is difficult. The new default store with vue3 is pinia which also supports vue2. For this reason migration to pinia as store is a good step. Furthermore pinia supports typescript out of the box.

Pinia can be used in parallel to the existing vuex store.

Homepage:
https://pinia.vuejs.org/

Migration:
https://pinia.vuejs.org/cookbook/migration-vuex.html#converting-a-single-module

**Comment by Cepheid-UK** [comment]
I think it would be good to migrate to Vue3 entirely, I believe the main thing holding us back was Vuetify support for it.
